# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile

FROM python:3.12-alpine

# Install build dependencies if needed
RUN apk update && apk add --no-cache gcc musl-dev linux-headers

# Set work directory
WORKDIR /app

# Copy all files
COPY . /app

# Upgrade pip and install the package
RUN pip install --no-cache-dir --upgrade pip \
    && pip install .

# Expose any ports if necessary (optional)

# Run the MCP server
CMD ["mcps"]
